import { useState } from 'react';
import { useRouter } from 'next/router';
import { useAuth } from '../../contexts/AuthContext';

export default function LoginPage() {
  const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
      const { login } = useAuth();
        const router = useRouter();

          const handleSubmit = async (e) => {
              e.preventDefault();
                  try {
                        await login(email, password);
                              router.push('/'); // Redireciona para a página principal após login
                                  } catch (error) {
                                        alert('Erro no login: ' + error.message);
                                            }
                                              };

                                                return (
                                                    <div className="min-h-screen flex items-center justify-center bg-gray-100">
                                                          <div className="bg-white p-8 rounded shadow-md w-96">
                                                                  <h1 className="text-2xl font-bold mb-6 text-center">Login Urna Eletrônica</h1>
                                                                          <form onSubmit={handleSubmit}>
                                                                                    <div className="mb-4">
                                                                                                <label className="block text-gray-700 mb-2" htmlFor="email">
                                                                                                              Email
                                                                                                                          </label>
                                                                                                                                      <input
                                                                                                                                                    id="email"
                                                                                                                                                                  type="email"
                                                                                                                                                                                className="w-full px-3 py-2 border rounded"
                                                                                                                                                                                              value={email}
                                                                                                                                                                                                            onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                          <div className="mb-6">
                                                                                                                                                                                                                                                                      <label className="block text-gray-700 mb-2" htmlFor="password">
                                                                                                                                                                                                                                                                                    Senha
                                                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                          id="password"
                                                                                                                                                                                                                                                                                                                                        type="password"
                                                                                                                                                                                                                                                                                                                                                      className="w-full px-3 py-2 border rounded"
                                                                                                                                                                                                                                                                                                                                                                    value={password}
                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                            type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Entrar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }